name: Backend CI/CD

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Deployment target"
        required: true
        default: cloudrun
        type: choice
        options:
          - cloudrun
          - gke

env:
  PROJECT_ID: my-project-95-480908
  REGION: us-central1
  REPOSITORY: backend-repo
  IMAGE_NAME: backend-app
  DEPLOY_TARGET: cloudrun

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/550659200096/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci-sa@my-project-95-480908.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build \
            -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA} .

      - name: Push Docker image
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}

      # -------- Cloud Run path --------
      - name: Deploy to Cloud Run
        if: env.DEPLOY_TARGET == 'cloudrun'
        run: |
          gcloud run deploy backend-service \
            --image "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}" \
            --region "${REGION}" \
            --platform managed \
            --service-account "backend-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
            --allow-unauthenticated

      # -------- GKE path --------
      - name: Get GKE credentials
        if: env.DEPLOY_TARGET == 'gke'
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --region ${REGION} \
            --project ${PROJECT_ID}

      - name: Deploy to GKE
        if: env.DEPLOY_TARGET == 'gke'
        run: |
          kubectl set image deployment/backend \
            backend=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}
